version: '3.8'

services:
  arena:
    image: arena:latest
    ports:
      - "7689:7689"
      - "7689:7689/udp"
    container_name: arena_service
    networks:
      - arena
    restart: always

networks:
  arena:
    driver: bridge